# Generated by Django 5.2.16 on 2026-07-18 13:30

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dcim", "0096_cablepath_add_fans_out_flags"),
        ("extras", "0146_computedfield_output_type"),
        ("ipam", "0058_iprange_role_data"),
        ("users", "0011_alter_user_default_saved_views"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("failover_policy", models.CharField(default="none", max_length=255)),
                ("max_wait_seconds", models.PositiveIntegerField(default=300)),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
                ),
            ],
            options={
                "verbose_name": "Execution Zone",
                "verbose_name_plural": "Execution Zones",
                "ordering": ["priority", "name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="JobDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=False)),
                ("image", models.CharField(max_length=255)),
                ("image_digest", models.CharField(max_length=255)),
                ("input_schema", models.JSONField(blank=True, default=dict)),
                ("zone_policy", models.CharField(default="pinned", max_length=255)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("timeout_seconds", models.PositiveIntegerField(default=1800)),
                ("grace_seconds", models.PositiveIntegerField(default=30)),
                ("retry_max", models.PositiveSmallIntegerField(default=0)),
                ("singleton", models.BooleanField(default=False)),
                ("dryrun_supported", models.BooleanField(default=False)),
                ("requires_zone_local", models.BooleanField(default=True)),
                (
                    "default_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pinned_job_definitions",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
                (
                    "secrets_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="remote_job_definitions",
                        to="extras.secretsgroup",
                    ),
                ),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
                ),
            ],
            options={
                "verbose_name": "Job Definition",
                "verbose_name_plural": "Job Definitions",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RemoteJobSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("interval", models.CharField(default="once", max_length=255)),
                ("crontab", models.CharField(blank=True, max_length=255)),
                ("start_time", models.DateTimeField()),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="nautobot_remote_jobs.jobdefinition",
                    ),
                ),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Job Schedule",
                "verbose_name_plural": "Remote Job Schedules",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("draining", models.BooleanField(default=False)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("capacity", models.PositiveSmallIntegerField(default=4)),
                ("agent_version", models.CharField(blank=True, max_length=255)),
                ("identity_fingerprint", models.CharField(max_length=255)),
                ("secret_generation", models.PositiveIntegerField(default=0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workers",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="RemoteJobRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "state",
                    models.CharField(db_index=True, default="PENDING", max_length=255),
                ),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("dryrun", models.BooleanField(default=False)),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("image_digest_executed", models.CharField(blank=True, max_length=255)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_job_runs",
                        to="dcim.device",
                    ),
                ),
                (
                    "job_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="nautobot_remote_jobs.jobdefinition",
                    ),
                ),
                (
                    "job_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remote_job_run",
                        to="extras.jobresult",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="nautobot_remote_jobs.remotejobrun",
                    ),
                ),
                (
                    "scoped_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.token",
                    ),
                ),
                (
                    "tags",
                    nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="nautobot_remote_jobs.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Job Run",
                "verbose_name_plural": "Remote Job Runs",
                "ordering": ["-queued_at"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="WorkerEnrollmentToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("expires", models.DateTimeField()),
                ("single_use", models.BooleanField(default=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollment_tokens",
                        to="nautobot_remote_jobs.worker",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_tokens",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Worker Enrollment Token",
                "verbose_name_plural": "Worker Enrollment Tokens",
                "ordering": ["-expires"],
            },
        ),
        migrations.CreateModel(
            name="ZoneFailover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=100)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failover_sources_through",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failover_targets",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone", "order"],
            },
        ),
        migrations.AddField(
            model_name="executionzone",
            name="failover_zones",
            field=models.ManyToManyField(
                blank=True,
                related_name="failover_sources",
                through="nautobot_remote_jobs.ZoneFailover",
                through_fields=("zone", "target"),
                to="nautobot_remote_jobs.executionzone",
            ),
        ),
        migrations.CreateModel(
            name="ZoneMembershipRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("include_descendant_locations", models.BooleanField(default=True)),
                ("weight", models.PositiveIntegerField(default=100)),
                (
                    "dynamic_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="extras.dynamicgroup",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(blank=True, related_name="+", to="dcim.location"),
                ),
                (
                    "prefixes",
                    models.ManyToManyField(blank=True, related_name="+", to="ipam.prefix"),
                ),
                (
                    "roles",
                    models.ManyToManyField(blank=True, related_name="+", to="extras.role"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_rules",
                        to="nautobot_remote_jobs.executionzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone Membership Rule",
                "verbose_name_plural": "Zone Membership Rules",
                "ordering": ["zone", "weight"],
            },
        ),
        migrations.CreateModel(
            name="RunArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("storage_path", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("uploaded", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="nautobot_remote_jobs.remotejobrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Run Artifact",
                "verbose_name_plural": "Run Artifacts",
                "ordering": ["run", "name"],
                "unique_together": {("run", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="remotejobrun",
            index=models.Index(
                fields=["state", "zone", "queued_at"],
                name="nautobot_re_state_76fc26_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="zonefailover",
            unique_together={("zone", "target")},
        ),
    ]
